// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3PvPKLEQEGNa8ueIPVMEdysWKv0kfBwk',
    appId: '1:822482765454:web:284db4f22070d631dbabdf',
    messagingSenderId: '822482765454',
    projectId: 'f290-ldm-poc-pi6',
    authDomain: 'f290-ldm-poc-pi6.firebaseapp.com',
    storageBucket: 'f290-ldm-poc-pi6.appspot.com',
    measurementId: 'G-V7HCGFNFTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOWt-88MzntgxmJA_1ylBqICidvtxLPU0',
    appId: '1:764721624862:android:6811179d661443c410fb0f',
    messagingSenderId: '764721624862',
    projectId: 'guiame-mobile',
    storageBucket: 'guiame-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmg1uUoj4A0FsJAAIZ4zQVCtHTd1nG_P0',
    appId: '1:822482765454:ios:71932cf6b588352fdbabdf',
    messagingSenderId: '822482765454',
    projectId: 'f290-ldm-poc-pi6',
    storageBucket: 'f290-ldm-poc-pi6.appspot.com',
    iosBundleId: 'br.com.fatecararas.f290DsmLdmPocPi6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmg1uUoj4A0FsJAAIZ4zQVCtHTd1nG_P0',
    appId: '1:822482765454:ios:8cd12705f2d00326dbabdf',
    messagingSenderId: '822482765454',
    projectId: 'f290-ldm-poc-pi6',
    storageBucket: 'f290-ldm-poc-pi6.appspot.com',
    iosBundleId: 'br.com.fatecararas.f290DsmLdmPocPi6.RunnerTests',
  );
}
