version: '3.8'

services:
  postgres:
    image: postgres:14.0-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_PASSWORD: guiame_cruds
      POSTGRES_USER: guiame_cruds
      POSTGRES_DB: guiame_cruds
