FROM eclipse-temurin:17-jdk-alpine AS builder

WORKDIR /app

COPY . .

RUN ./gradlew :consumidor:bootJar

# Usa steps para reduzir tamanho final da imagem, já que a imagem
# JRE é quase 90mb menor do que a imagem JDK
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

COPY --from=builder /app/consumidor/build/libs/consumidor-0.0.1-SNAPSHOT.jar consumidor.jar

ENTRYPOINT ["java", "-jar", "consumidor.jar"]
