firestore:
  collection: ${FIRESTORE_COLLECTION:eventos}
  project: ${FIRESTORE_PROJECT:guiame-mobile}

server:
  port: 3000

hibernate:
  connection:
    url: jdbc:postgresql://ep-misty-salad-49969234.us-east-1.aws.neon.tech/guiame-apicruds

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ep-misty-salad-49969234.us-east-1.aws.neon.tech/guiame-apicruds
    username: ghp2201
    password: D1ct7OsEPfIF

  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /docs/index.html
