// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZAIzLnjiE8dJxVju35nEojPKYvPQOmBQ',
    appId: '1:1040186223864:web:e784211666294e03b7df0d',
    messagingSenderId: '1040186223864',
    projectId: 'guiame-firestore-poc',
    authDomain: 'guiame-firestore-poc.firebaseapp.com',
    storageBucket: 'guiame-firestore-poc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmtqYkTdE2M1LTKULj7ppqjsDEx2Xz9zw',
    appId: '1:1040186223864:android:811a0b21e4fe9b96b7df0d',
    messagingSenderId: '1040186223864',
    projectId: 'guiame-firestore-poc',
    storageBucket: 'guiame-firestore-poc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe04A_uVmic16ZZi8Re14TaEdxJg9S8KI',
    appId: '1:1040186223864:ios:45c0a44e9c2034d8b7df0d',
    messagingSenderId: '1040186223864',
    projectId: 'guiame-firestore-poc',
    storageBucket: 'guiame-firestore-poc.appspot.com',
    iosBundleId: 'com.example.frontend',
  );
}
